include: []
exclude: []
formats:
  - 
    extension: 'py'
    top:
      enabled: true
      open: '"""'
      close: '"""'
      break_after_open: true
      break_before_close: true
    method:
      ignore:
        - __init__
      method_indicator: 'def'
      method_end: ':'
      regex: = false
      enabled: true
      indent: '4 spaces'
      indent_content: false
      doc_open: '"""'
      doc_close: '"""'
      comments:
        - '#'
      break_after_open: true
      break_after_docstring: true
      break_before_close: true
      words_per_line: 10
      before_method: true
    arguments:
      title: 'Parameters'
      underline: true
      add_type: true
      inline: false
      prefix: ''
      ignore:
        - cls
        - self
      start_parameter: '('
      end_parameter: ')'
      parameter_split: ','
      regex: false
    returns:
      return_title: 'Return Values'
      return_underline: true
      return_add_type: true
      return_inline: false
      return_prefix: ''
      return_ignore:
      return_start_parameter: 'return'
      return_end_parameter: 
      return_parameter_split: ','
      return_regex: false
     
    class:
      class_indicator: 'class'
      class_end_name: '('
      class_end: ':'
      regex: false
      doc_open: '"""'
      doc_close: '"""'
      indent: '4 spaces'
      indent_content: true
      break_after_open: false
      break_after_docstring: false
      break_before_close: false
      words_per_line: 10
      before_class: true



