include: []
exclude: []
formats:
  - 
    extension: 'py'
    top:
      enabled: true
      open: '"""'
      close: '"""'
      break_after_open: true
      break_before_close: true
    method:
      ignore:
        - __init__
      method_indicator: 'def'
      method_end: ':'
      regex: = false
      enabled: true
      indent: '4 spaces'
      indent_content: false
      doc_open: '"""'
      doc_close: '"""'
      comments:
        - '#'
      break_after_open: true
      break_after_docstring: true
      break_before_close: true
      words_per_line: 10
      before_method: true
    arguments:
      title: 'Parameters'
      underline: true
      add_type: true
      inline: false
      prefix: ''
      ignore:
        - cls
        - self
      start_parameter: '('
      end_parameter: ')'
      parameter_split: ','
      regex: false
    class:
      start_indicator: 'class'
